---
title: "length-com-pilot"
output: html_document
---

```{r load-libraries, library, message=F, results='hide', warning=FALSE}
library(tidyverse)
library(here)
library(knitr)
library(tidyboot)
library(lme4)
library(broom.mixed)
library(RColorBrewer)
library(DT)
library(ggthemes)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)
theme_set(theme_classic(base_size = 16))
```

```{r read-csv}
raw_data <- read.csv(here("data/run_2_within_ss.csv")) %>%
  filter(test_part == "box_selection" | test_part == "comment") %>%
  mutate(accuracy = as.numeric(accuracy),
         rt = rt/1000)

raw_ref_data <- read.csv(here("data/2obj_data.csv")) %>%
  filter(test_part == "obj_selection" | test_part == "comment") %>%
  mutate(accuracy = as.numeric(accuracy))

raw_ref4_data <- read.csv(here("data/4obj_data.csv")) %>%
  filter(test_part == "obj_selection" | test_part == "comment") %>%
  mutate(accuracy = as.numeric(accuracy))

raw_novel4_data <- read.csv(here("data/novel4_data.csv")) %>%
  #filter(!(test_part == "check" & button_pressed != "0"))
  filter(test_part == "obj_selection" | test_part == "comment" | test_part == "check") %>%
  mutate(accuracy = as.numeric(accuracy))

raw_new4_data <- read.csv(here("data/new4_data.csv")) %>%
  filter(test_part == "obj_selection" | test_part == "comment" | test_part == "check") %>%
  mutate(accuracy = as.numeric(accuracy))
```

```{r subjs}
keep_subs <- raw_data %>%
  filter(test_part == "box_selection") %>%
  group_by(subid) %>%
  summarise(n = n_distinct(selected_box)) %>%
  filter(n > 1)

ref_keep_subs <- raw_ref4_data %>%
  filter(test_part == "obj_selection") %>%
  group_by(subid) %>%
  summarise(n = n_distinct(selected_obj)) %>%
  filter(n > 1)

novel_check <- raw_novel4_data %>%
  mutate(check = ifelse(test_part == "check", button_pressed, 0)) %>%
  filter(check > 0)

novel_keep_subs <- raw_novel4_data %>%
  filter(!(subid %in% novel_check$subid)) %>%
  filter(test_part == "obj_selection") %>%
  group_by(subid) %>%
  mutate(n = n_distinct(selected_utt)) %>%
  filter(n > 1)

failed_check <- raw_new4_data %>%
  mutate(check = ifelse(test_part == "check", button_pressed, 0)) %>%
  filter(check > 0)

new_keep_subs <- raw_new4_data %>%
  filter(test_part == "obj_selection") %>%
  filter(!(subid %in% failed_check$subid)) %>%
  group_by(subid) %>%
  mutate(n = n_distinct(selected_utt)) %>%
  filter(n > 1)
```

```{r analysis}
subj_data <- raw_data %>%
  filter(subid %in% keep_subs$subid, test_part == "box_selection") %>%
  mutate(chose_complex = if_else(selected_box == "box_2", 1, 0)) %>%
  pivot_longer(cols = c(accuracy, rt, chose_complex), names_to = "measure")

mean_data <- subj_data %>%
  group_by(measure, boxes_type, utt) %>%
  tidyboot_mean(value)

ref_data <- raw_ref_data %>%
  filter(test_part == "obj_selection") %>%
  mutate(chose_complex = if_else(selected_obj == "complex.png", 1, 0)) %>%
  pivot_longer(cols = c(accuracy, rt, chose_complex), names_to = "measure") %>%
  group_by(measure, utt) %>%
  tidyboot_mean(value)

ref4_data <- raw_ref4_data %>%
  filter(subid %in% ref_keep_subs$subid) %>%
  filter(test_part == "obj_selection") %>%
  mutate(chose_complex = if_else(selected_obj == "complex.png", 1, 0)) %>%
  pivot_longer(cols = c(accuracy, rt, chose_complex), names_to = "measure") %>%
  group_by(measure, utt) %>%
  tidyboot_mean(value)

novel4_data <- raw_novel4_data %>%
  filter(subid %in% novel_keep_subs$subid, test_part == "obj_selection") %>%
  mutate(chose_complex = if_else(selected_utt == "complex_utt", 1, 0)) %>%
  pivot_longer(cols = c(accuracy, rt, chose_complex), names_to = "measure") %>%
  group_by(measure, obj) %>%
  tidyboot_mean(value)

new4_data <- raw_new4_data %>%
  filter(subid %in% new_keep_subs$subid, test_part == "obj_selection") %>%
  mutate(chose_complex = if_else(selected_utt == "complex_utt", 1, 0)) %>%
  pivot_longer(cols = c(accuracy, rt, chose_complex), names_to = "measure") %>%
  group_by(measure, obj) %>%
  tidyboot_mean(value)
```

```{r plot, fig.width = 5, fig.height = 4}
ggplot(mean_data %>% filter(measure == "accuracy"),
       aes(fill = utt, x = boxes_type, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "", y = "accuracy") + 
  scale_fill_ptol()

ggplot(mean_data %>% filter(measure == "rt"),
       aes(fill = utt, x = boxes_type, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  labs(x = "", y = "response time (sec)") + 
  scale_fill_ptol()

ggplot(mean_data %>% filter(measure == "chose_complex"),
       aes(fill = utt, x = boxes_type, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "", y = "chose complex (prop.)") + 
  scale_fill_ptol()
```

```{r ref plots, fig.width=5, fig.height=4}
# reference plots

ggplot(ref_data %>% filter(measure == "chose_complex"),
       aes(fill = utt, x = utt, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "", y = "chose complex (prop.)") + 
  scale_fill_ptol()

# 4 objects

ggplot(ref4_data %>% filter(measure == "chose_complex"),
       aes(fill = utt, x = utt, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "", y = "chose complex (prop.)") + 
  scale_fill_ptol()

ggplot(ref4_data %>% filter(measure == "accuracy"),
       aes(fill = utt, x = utt, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "utterance type", y = "accuracy") + 
  scale_fill_ptol()

# novel 4 objects

ggplot(novel4_data %>% filter(measure == "chose_complex"),
       aes(fill = obj, x = obj, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "object type", y = "accuracy") + 
  scale_fill_ptol()

ggplot(novel4_data %>% filter(measure == "accuracy"),
       aes(fill = obj, x = obj, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "object type", y = "accuracy") + 
  scale_fill_ptol()

#new 4 objects

ggplot(new4_data %>% filter(measure == "accuracy"),
       aes(fill = obj, x = obj, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "object type", y = "accuracy") + 
  scale_fill_ptol()

ggplot(new4_data %>% filter(measure == "chose_complex"),
       aes(fill = obj, x = obj, y = empirical_stat)) +
  geom_bar(position="dodge", stat="identity") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                width = 0.2, position=position_dodge(.9)) + 
  geom_hline(aes(yintercept = .5), linetype = "dashed") + 
  labs(x = "object type", y = "prop. choosing complex") + 
  scale_fill_ptol()

```

```{r list-responses}
raw_data %>% 
  group_by(subid) %>%
  filter(test_part == "comment") %>% 
  select(responses) %>%
  datatable()

raw_ref4_data %>%
  filter(subid %in% ref_keep_subs$subid) %>%
  group_by(subid) %>%
  filter(test_part == "comment") %>% 
  select(responses) %>%
  datatable()
```

