---
title: "process_mturk_data"
output: html_document
---
```{r load_libraries}
library(tidyverse)
library(here)
library(ggthemes)
library(tidyboot)
library(rjson)
library(jsonlite)
library(anonymizer)

theme_set(theme_classic(base_size = 18))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read-csv}
read_file <- function(file) {

  path = paste("raw_data/run_2_within_ss/", file, sep = "")
  csv_out <- read_csv(here(path))
  id <- str_remove(file, ".csv")
  csv_out$subid <- rep(id, nrow(csv_out))
 
 return(csv_out)
}

file_list <- list.files(path = here("raw_data/run_2_within_ss/"), pattern = "\\.csv$")

raw_data <- map(file_list, read_file) %>%
  bind_rows() %>%
  rename(left_box = box_1, right_box = box_2) %>%
  mutate(responses = str_remove_all(responses, "[\"{Q}0:]"),
         left_box = str_remove(left_box, "num_objects/"),
         left_box = str_remove(left_box, "num_types/"),
         right_box = str_remove(right_box, "num_objects/"),
         right_box = str_remove(right_box, "num_types/"),
         selected_box = if_else(test_part == "box_selection", 
                               ifelse(button_pressed == 1, right_box, left_box), ""),
         accuracy = if_else(test_part == "box_selection",
                            if_else(selected_box == "box_1" & utt == "simple_utt" |
                                      selected_box == "box_2" & utt == "complex_utt", 
                                    1, 0), 0))
  


#write_csv(raw_data, here("data/run_2_within_ss.csv"))
```


```{r load data}

files <- list.files(here("raw_data/run_1_btwn_ss"), pattern = "*.json", full.names = T)

df <- lapply(files, fromJSON)
res <- lapply(df, summary)


for(i in 1:length(df)){
  tmp_trials <- df[[i]]$answers$data
  data <- read.csv(textConnection(tmp_trials))
}

#read_file <- function(file, newnames) {
#  
#  json_out <- fromJSON(file)
#  id <- json_out$WorkerId
#  
#  raw_data <- json_out$answers$data 
#  firstrow <- strsplit(raw_data[1], split = ",")[[1]] %>%
#    str_trim()
  
#  data <- raw_data[] %>%
#    as_tibble() %>%
#    separate(value, into = firstrow, sep = ",") %>%
#    mutate(subid = id)
#}

#raw_data <- map(files, read_file) %>%
#  bind_rows() %>%
#  filter(counter != " counter") %>%
#  mutate(subid = salt(subid, .seed = 400)) %>%
#  mutate(subid = as.numeric(as.factor(subid)))

#write_csv(raw_data, here("data/turk_data.csv"))

```

```{r process jspsych data}

filenames <- list.files(here("production-results/"), pattern = "*.json", full.names = T)

ldf <- lapply(filenames, fromJSON)
jsdata = NULL

for(i in 1:length(ldf)){
  tmp_trials <- ldf[[i]]$answers$data
  tmp <- read.csv(textConnection(tmp_trials))
  if (length(tmp$stimulus) > 8) {
    tmp_data <- tmp[c(8,9,10),] %>%
      select(c(rt, button_pressed, test_part, utt, boxes_type, 
               box_1, box_2, responses)) %>%
      rename(left_box = box_1, right_box = box_2) %>%
      mutate(subid = as.numeric(i),
         responses = str_remove_all(responses, "[\"{Q}0:]"),
         left_box = str_remove(left_box, "num_objects/"),
         left_box = str_remove(left_box, "num_types/"),
         right_box = str_remove(right_box, "num_objects/"),
         right_box = str_remove(right_box, "num_types/"),
         selected_box = if_else(test_part == "box_selection", 
                               ifelse(button_pressed == 1, right_box, left_box), ""),
         accuracy = if_else(test_part == "box_selection",
                            if_else(selected_box == "box_1" & utt == "simple_utt" |
                                      selected_box == "box_2" & utt == "complex_utt", 
                                    1, 0), 0))
    jsdata <- rbind(jsdata, tmp_data)
  }
}

write_csv(jsdata, here("data/jspsych_data.csv"))

```


```{r unique workers}
dfiles <- list.files(here("mturk/3objects/run 1/production-results/"), pattern = "*.json", full.names = T)

allworkers <- lapply(dfiles, fromJSON)
workers = NULL

for(i in 1:length(allworkers)) {
  id <- allworkers[[i]]$WorkerId
  workers <- rbind(workers, id)
}

workers <- as.data.frame(workers) %>%
  rename(id = V1) %>%
  mutate(duplicate = duplicated(workers)) %>%
  mutate(num = 1:n())

#write_csv(workers, here("mturk/2objworkers.csv"))
#write_csv(workers, here("mturk/4objworkers.csv"))
write_csv(workers, here("mturk/new4workers.csv"))

```

```{r process reference data}

filenames <- list.files(here("mturk/familiar4objects/production-results-anon/"), pattern = "*.json", full.names = T)

duplicates <- read.csv(here("mturk/2objworkers.csv")) %>%
  mutate(id = as.character(id)) %>%
  filter(duplicate == TRUE)

ldf <- lapply(filenames, fromJSON)
jsdata = NULL

for(i in 1:length(ldf)){
  #if(i != duplicates$num[1] & i != duplicates$num[2]){
    tmp_trials <- ldf[[i]]$answers$data
    tmp <- read.csv(textConnection(tmp_trials))
    tmp_data <- tmp %>%
        select(c(rt, button_pressed, test_part, utt_1, utt_2, 
                 cue, trial_index, responses)) %>%
        mutate(subid = as.numeric(i),
           responses = str_remove_all(responses, "[\"{Q}0:]"),
           cue = str_remove(cue, "img/"),
           utt_1 = as.character(utt_1),
           utt_2 = as.character(utt_2),
           selected_utt = if_else(test_part == "obj_selection", 
                     ifelse(button_pressed == "0", utt_1, utt_2), ""),
           accuracy = if_else(test_part == "obj_selection",
                          if_else(
                                selected_utt == "complex_utt" & trial_index == 8 |
                                selected_utt == "simple_utt" & trial_index == 9, 
                                1, 0), 
                          if_else(test_part == "check",
                                  if_else(button_pressed == "1", 1, 0), 0))
           )
      #new_data <- tmp_data %>%
       # mutate(obj = if_else(test_part == "obj_selection", 
        #             tmp_data$obj %>% replace(1,
         #                             ifelse(tmp_data$obj[2] == "complex.png",
          #                                   "simplenovel.png","complex.png")), ""),
           #    accuracy = if_else(test_part == "obj_selection",
            #              if_else(
             #                  selected_utt == "complex_utt" & obj == "simplenovel.png" |
              #                  selected_utt == "simple_utt" & obj == "complexnovel.png", 
               #                 1, 0), 0))
      jsdata <- rbind(jsdata, tmp_data)
    #}
  }

write_csv(jsdata, here("data/familiar4_data.csv"))

```